### ISSUE TITLE
hpvsim - local doc build failing (make html)

### ISSUE THREAD

**Issue by RCarter-IDM** [InstituteforDiseaseModeling/hpvsim#4]
Following error after running 'make html' from fpsim/docs:

Notebook error:
PandocMissing in tutorials\tut_analyzers.ipynb:
Pandoc wasn't found.

**Comment by RCarter-IDM** [comment]
steps to duplicate:

python -m venv virt-hpvsim (create virtual environment)
scripts\activate (activate virtual environment)
git clone https://github.com/RCarter-IDM/hpvsim.git (clone, after first creating fork)
pip install -e . (install from cloned repo, local)
pip install -r requirements.txt (from /docs dir)
make html (from /docs dir)

**Comment by JSchripsema-IDM** [comment]
@RCarter-IDM pandoc is listed in docs/requirements.txt so your local environment should find it. Sometimes I have to close the command window and open a new one before running `make html` the first time--maybe this is it? I also usually run `python -m pip install -e .` to install the package from local code (just running pip install gave me version errors). 
```
reading sources... [ 80%] tutorials/tut_analyzers
Notebook error:
CellTimeoutError in tutorials\tut_analyzers.ipynb:
A cell timed out while it was being executed, after 90 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['import numpy as np', 'import sciris as sc', 'import hpvsim as hpv', '', '# Create some parameters, setting beta (per-contact transmission probability) higher']
...
['', 'sim = hpv.Sim(pars, genotypes=[16, 18], analyzers=[az1])', 'sim.run()', 'a = sim.get_analyzer()', 'a.plot();']
-------------------

Task was destroyed but it is pending!
task: <Task pending name='Task-18' coro=<NotebookClient._async_poll_output_msg() running at c:\users\jensc\venv\hpvsim\lib\site-packages\nbclient\client.py:806> wait_for=<Future pending cb=[Task.__wakeup()]>>
```

**Comment by cliffckerr** [comment]
@JSchripsema-IDM @RCarter-IDM Ah, looks like it's just timing out. It's set to timeout after 90 seconds, which at the time I thought was extremely generous :grin: I think it's just this line that would need to change:
https://github.com/InstituteforDiseaseModeling/hpvsim/blob/develop/docs/conf.py#L234

**Comment by JSchripsema-IDM** [comment]
Thanks @cliffckerr -- I tried doubling the timeout limit and solved that error. Now I'm seeing the same type error the RTD build is hitting in #62. 

TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

You can ignore this error by setting the following in conf.py:

    nbsphinx_allow_errors = True

**Comment by cliffckerr** [comment]
@JSchripsema-IDM Yes, we just encountered this too. Weird that it didn't occur earlier!

**Comment by cliffckerr** [comment]
(Just to be clear, this is due to two bugs that happened to cancel each other out, and one bug was fixed, which then revealed the other bug, so please do _not_ pin this version in order to make this work! :joy: :sob:)

**Comment by cliffckerr** [comment]
This has been fixed! If you merge `main` into your branch, it should work now.
