### ISSUE TITLE
hpvsim - makedocs - ERROR: Failed building wheel for pandoc

### ISSUE THREAD

**Issue by RCarter-IDM** [InstituteforDiseaseModeling/hpvsim#6]
This is on a linux VM (Ubuntu v20). pip list shows pandoc 2.3 is installed. This fails during 'make html' in docs folder.

Resolution is to use 'apt-get' to install pandoc: "sudo apt-get -y install pandoc"

**Comment by JSchripsema-IDM** [comment]
Investigate what version of Linux RTD uses for builds (HPVsim passing there) and close out if the Linux build looks good.

**Comment by RCarter-IDM** [comment]
It appears that Linux RTD servers may be using Ubuntu 22.04, per https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

**Comment by RCarter-IDM** [comment]
Excerpts below are from here: https://stackoverflow.com/questions/62398231/building-docs-fails-due-to-missing-pandoc

..."It's currently not very well explained on the [PyPI page for pandocs](https://pypi.org/project/pandoc/), but pandoc is actually written in Haskell, not Python. The pandoc package for python which you can install with pip install pandoc doesn't come with an executable copy of pandoc, it is just a wrapper to provide bindings to pandoc within python. It does this by making shell calls to your system copy of pandoc, and so you need to separately [install a copy of the actual pandoc executable](https://pandoc.org/installing.html) to your system in order for the python bindings to have something to bind to!

For example, on Debian/Ubuntu, you will need to install a system copy of pandoc using apt in addition to installing the python bindings with pip.

sudo apt install pandoc
pip install pandoc
"...

**Comment by RCarter-IDM** [comment]
The fact that it works on RTD server *may* be because they're using Conda (see excerpt below from https://stackoverflow.com/questions/62398231/building-docs-fails-due-to-missing-pandoc) or that they've already setup/installed pandoc in their environment.

..."In contrast to this, conda tries to make packages work irrespective of things installed on the rest of your system. Hence the conda pandoc package ships with an actual copy of pandoc, which it uses instead of trying to use your system copy of pandoc. If you're using conda, there is only one command you need to run to get pandoc working within python:

conda install pandoc
If you're using a conda environment for your readthedocs specification (as is the situation for OP), you can just add pandoc to the conda section instead of the pip section of the env."...

**Comment by RCarter-IDM** [comment]
https://github.com/InstituteforDiseaseModeling/doc-guidance/pull/37

**Comment by RCarter-IDM** [comment]
PR merged
